### ISSUE TITLE
The `compare` Implementation On Version Is Inconsistent with `equals` And Invalid For PVP

### ISSUE THREAD

**Issue by isomarcte** [coursier/versions#13]
The implementation of the `compare` method on `Version` is inconsistent with `equals`.

```scala
scala> val a: Version = Version("1")
val a: coursier.version.Version = Version(1)

scala> val b: Version = Version("1.0")
val b: coursier.version.Version = Version(1.0)

scala> a.compareTo(b)
val res0: Int = 0

scala> a == b
val res1: Boolean = false
```

It is also inconsistent with `hashCode`. 

```scala
scala> a.hashCode == b.hashCode
val res3: Boolean = false
```

It is also incorrect if one assumes the version scheme is [pvp][pvp]. From the specification for PVP,

> Version number ordering is already defined by Cabal as the lexicographic ordering of the components. For example, 2.0.1 > 1.3.2, and 2.0.1.0 > 2.0.1. (The Data.Version.Version type and its Ord instance embody this ordering).

The important example there being that `2.0.1.0 > 2.0.1`, not equal.

This means that the current `compare` definition for `Version` is incorrect if that version is supposed to represent a PVP version.

```scala
scala> Version("1.0.0").compare(Version("1.0.0.0"))
val res0: Int = 0
```

According to PVP, these should compare the same as,

```scala
scala> "1.0.0".compare("1.0.0.0")
val res2: Int = -2
```

I'm not exactly sure how this can easily be fixed. If for a moment we ignore the PVP use case and just focus on `equals` and `hashCode`, then we could resolve the issue using #12. This works, but as noted on the PR, the behavior here is likely unexpected for most users, though technically valid.

```scala
scala> Set(Version("1.0.0"), Version("1.0"), Version("1.0.0+SOME_META"))
val res0: scala.collection.immutable.Set[coursier.version.Version] = Set(Version(1.0.0))
```

On the other hand, we could redefine `compare` to just be lexicographic ordering and introduce a new method for comparing the expressed binary API with respect to a specific `VersionCompatibility` value. This https://github.com/isomarcte/versions/tree/fix-pvp-ordering has some work towards that front, however I paused on it as I'm pretty concerned that changing the definition of compare may have negative effects on `coursier` as a whole, though this does seem like the more viable solution to me.

Another option would be to change the definition for `compare` _and_ introduce a new type which is effectively a tuple a `Version` and a `VersionCompatibility`. This could provide methods to attempt to compare binary APIs with respect to a specific version scheme, making the behavior more explicit.

Thoughts?

[pvp]: https://pvp.haskell.org/#version-numbers "PVP"

**Comment by alexarchambault** [comment]
Not sure why this slipped my attention for 3.5 years 😬

I kind of agree that the inconsistency between `compare` and `equals` can be surprising, but it's not totally inconsistent: if `a.compare(b) != 0`, we have `!a.equals(b)`. The only problem is that sometimes, `a.compare(b) == 0` while `!a.equals(b)`.

This behavior is mentioned in the [`java.lang.Comparable` javadoc](https://github.com/openjdk/jdk8/blob/6a383433a9f4661a96a90b2a4c7b5b9a85720031/jdk/src/share/classes/java/lang/Comparable.java#L50-L56) (`scala.math.Ordered` extends that interface). Seems it's only a problem for some sorted set / map implementations.

**Comment by alexarchambault** [comment]
That being said, I've tended to dislike compare returning 0 for versions with different representations (things like `1.0` and `1.0.0` for example, that you mention too, also `1.0` and `1.0+thing`). So I'll probably make the order total at some point…

**Comment by ghostbuster91** [comment]
We hit this from the Semver side and wanted to add evidence - it's the same root cause as this issue, but the downstream consequences in the resolver are worse than "`Set` and `TreeSet` disagree."

## Same law violation, different trigger

The PVP example here (`Version("1").compareTo(Version("1.0")) == 0` but `!=`) has a Semver §10 twin:

```scala
val a = Version("2.13.16+1.18.2")
val b = Version("2.13.16+1.19.0")

assert(a.compare(b) == 0)     // Semver §10 — build metadata ignored for ordering
assert(a != b)                // string-based equals on repr
assert(a.hashCode != b.hashCode)

assert(Set(a, b).size == 2)                                  // HashSet keeps both
assert(scala.collection.immutable.TreeSet(a, b).size == 1)   // TreeSet dedups
```

`compare` filters `BuildMetadata` tokens before comparing; `equals`/`hashCode` come from `@data class Version(repr)`, so the string wins there. One bug, two surface framings (PVP and Semver `+X`).

Worth flagging that the current Semver §10 behavior is documented by an existing test in `VersionTests.scala`:

```scala
test("buildMetadata") {
  test {
    assert(compare("1.2", "1.2+foo") == 0)
    assert(compare("2.0", "2.0+20130313144700") == 0)
    assert(compare("2.0+20130313144700", "2.0.2") < 0)

    // Semver § 10: two versions that differ only in the build metadata, have the same precedence
    assert(compare("1.2+bar", "1.2+foo") == 0)
    assert(compare("1.2+bar.1", "1.2+bar.2") == 0)
  }
```

## This actually breaks resolution - two ways

**1. Silent artifact substitution.** `VersionInterval.merge` uses `compare` only. When two intervals meet with `compare == 0`, the merge keeps the first-encountered bound regardless of `repr`. That's enough for the resolver to silently drop one of two pinned artifacts. Minimal reproducer against `coursier/coursier`'s test harness:

```scala
val projects = Seq(
  Project(mod"acme:s", "2.13.16+1.18.2"),
  Project(mod"acme:s", "2.13.16+1.19.0"),
  Project(mod"acme:x", "1.0",
    Seq(Variant.emptyConfiguration -> dep"acme:s:2.13.16+1.19.0")),
  Project(mod"acme:y", "1.0",
    Seq(Variant.emptyConfiguration -> dep"acme:s:2.13.16+1.18.2")),
  Project(mod"acme:app", "1.0", Seq(
    Variant.emptyConfiguration -> dep"acme:x:1.0",
    Variant.emptyConfiguration -> dep"acme:y:1.0"))
)

// After resolving acme:app:1.0 …
val sVersions = res.dependencies.iterator
  .filter(_.module == mod"acme:s")
  .map(_.versionConstraint.asString)
  .toSet

assert(sVersions.size == 1)                                    // one silently dropped
assert(res.conflicts.filter(_.module == mod"acme:s").isEmpty)  // no conflict surfaced
assert(res.errors0.filter(_._1._1 == mod"acme:s").isEmpty)     // no error surfaced
```

Runs green — the resolver visibly does the wrong thing, with no diagnostic.

**2. Non-terminating / CPU-bound resolution.** In graphs with enough transitive shape, the iteration loop keeps re-introducing compare-equal-but-distinct-`repr` variants; the dependency set grows without a fixed point, and `Resolution.reverseDependencies` (a `groupBy`) is recomputed on an ever-larger collection. Thread dumps from a stuck production build resolving Scala.js 2.13 artifacts:

```
"coursier-pool-1-thread-5" #151 daemon prio=5 cpu=180944.65ms elapsed=347.89s
   java.lang.Thread.State: RUNNABLE
    at scala.collection.IterableOps.groupBy(Iterable.scala:559)
    at coursier.core.Resolution.reverseDependencies$lzycompute(Resolution.scala:1713)
    at coursier.core.Resolution.remainingDependencies$lzycompute(Resolution.scala:1751)
    at coursier.core.Resolution.newDependencies$lzycompute(Resolution.scala:1759)
    at coursier.core.Resolution.nextNoMissingUnsafe(Resolution.scala:1771)
    at coursier.core.Resolution.nextIfNoMissing(Resolution.scala:1784)
    at coursier.core.ResolutionProcess$.apply(ResolutionProcess.scala:408)
    ...
```

Same frame in a second dump (180s later) - no I/O, no lock, 100% CPU in the `ResolutionProcess` iteration loop. Concrete real-world graph: `smithy4s-protocol_sjs1_2.13:0.13.54` (pulls `scalajs-scalalib:2.13.16+1.19.0`) resolved alongside `smithy4s-core_sjs1_2.13:0.18.35` (pulls `scalajs-scalalib:2.13.16+1.18.2`). Haven't shrunk to a synthetic reproducer yet.

One scoping note we haven't been able to explain: the hang only reproduces under sbt 2.0 (specifically during a MiMa run over that graph). The same dependency set under sbt 1.x resolves fine. Consequence #1 (silent substitution) is independent of the build tool - the reproducer above is pure `coursier.core.Resolution` - so the sbt-version dependency is presumably in how the two sbt lines drive coursier, not in coursier itself, but we haven't isolated it.

## Real-world impact

Scala.js publishes `scalajs-scalalib` using `<scalaVersion>+<scalaJsVersion>` (`2.13.16+1.18.2` vs `2.13.16+1.19.0`). These are genuinely different jars with different classfiles and different transitive graphs. Any project that transitively pulls in two Scala.js library versions pinning different `scalajs-scalalib` builds hits either consequence #1 (silent artifact swap -> runtime error that looks unrelated) or consequence #2 (resolution never returns).

## Preferred fix

**Make `compare` a total order** - use build-metadata / trailing PVP tokens as a tiebreaker instead of ignoring them. Restores the `Ordering` law. Breaks strict Semver §10, but §10's rationale ("metadata is display-only") doesn't apply when downstream tooling - Scala.js uses that metadata to distinguish artifacts.

Happy to open a PR once the direction is settled.
